services:
  - type: web
    name: homestaytayninh-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYMENT_PROVIDER
        value: mock-apipay
      - key: APIPAY_BASE_URL
        sync: false
      - key: APIPAY_CREATE_PAYMENT_PATH
        sync: false
      - key: APIPAY_ACCESS_KEY
        sync: false
      - key: APIPAY_SECRET_KEY
        sync: false
      - key: APIPAY_CURRENCY
        value: VND
      - key: APIPAY_RETURN_URL
        sync: false
      - key: APIPAY_CALLBACK_URL
        sync: false
      - key: AUTH_MODE
        value: supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: WEB_ORIGIN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: RABBITMQ_URL
        sync: false
