services:
  - type: web
    name: homestaytayninh-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAYMENT_PROVIDER
        value: apipay
      - key: APIPAY_BASE_URL
        value: https://app.apipay.vn
      - key: APIPAY_CREATE_PAYMENT_PATH
        value: /v1/client/payment-requests
      - key: APIPAY_BANK_PUBLIC_ID
        sync: false
      - key: APIPAY_ACCESS_KEY
        sync: false
      - key: APIPAY_SECRET_KEY
        sync: false
      - key: APIPAY_RETURN_URL
        value: https://homestaytayninh-frontend.vercel.app/payment/result
      - key: APIPAY_CALLBACK_URL
        value: https://homestaytayninh-backend.onrender.com/api/payments/apipay/webhook
      - key: APIPAY_WEBHOOK_CREATE_PATH
        value: /v1/client/webhooks
      - key: APIPAY_WEBHOOK_TYPE
        value: IN
      - key: WEB_ORIGIN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SESSION_TTL_SECONDS
        value: "604800"
      - key: REDIS_AUTO_SEED
        value: "true"
      - key: REDIS_SEED_DEMO
        value: "true"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: RABBITMQ_URL
        sync: false
