-- RLS is defined and versioned in:
-- prisma/migrations/20260526103000_homestay_mvp_schema/migration.sql
--
-- Public Data API access is deliberately read-only:
-- - homestays, rooms, room_rates, homestay_images, amenities, services, reviews
-- - published articles only
--
-- Server-side writes for booking, payment, owner, staff and admin flows must use
-- a backend secret/service credential or a PostgreSQL connection. Do not create
-- anon write policies to make server endpoints work.
